server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  redis:
     host: 127.0.0.1
     port: 6379
     password:
spring:
  devtools:
      restart:
        enabled: true
        exclude: WEB-INF/**
        additional-paths:
          - src/main/java